// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website_Klinik.Data;

#nullable disable

namespace Website_Klinik.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Website_Klinik.Models.TBL_ALAMAT", b =>
                {
                    b.Property<int>("ID_ALAMAT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ALAMAT"), 1L, 1);

                    b.Property<string>("JALAN_PERUMAHAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KABUPATEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KECAMATAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KOTA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROVINSI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RT_RW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_ALAMAT");

                    b.ToTable("TBL_ALAMATs");
                });

            modelBuilder.Entity("Website_Klinik.Models.TBL_PASIEN", b =>
                {
                    b.Property<int>("ID_PASIEN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PASIEN"), 1L, 1);

                    b.Property<string>("AGAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ALAMATID_ALAMAT")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL_PASIEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JENIS_KELAMIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFIED_BY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAMA_PASIEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOMOR_TELEPON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PEKERJAAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGISTER_BY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REKAM_MEDIS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS_KAWIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TANGGAL_LAHIR")
                        .HasColumnType("datetime2");

                    b.Property<string>("TEMPAT_LAHIR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMUR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PASIEN");

                    b.HasIndex("ALAMATID_ALAMAT");

                    b.ToTable("TBL_PASIENs");
                });

            modelBuilder.Entity("Website_Klinik.Models.TBL_PENDAFTARAN", b =>
                {
                    b.Property<int>("ID_PENDAFTARAN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PENDAFTARAN"), 1L, 1);

                    b.Property<string>("DIBUAT_OLEH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIUPDATE_OLEH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_ADMIN")
                        .HasColumnType("int");

                    b.Property<int>("ID_OBAT")
                        .HasColumnType("int");

                    b.Property<int>("ID_PASIEN")
                        .HasColumnType("int");

                    b.Property<string>("ID_TINDAKAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KONSULTASI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAMA_PASIEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PASIENID_PASIEN")
                        .HasColumnType("int");

                    b.Property<string>("REKAM_MEDIS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS_FORM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TANGGAL_BEROBAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TANGGAL_DIBUAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TANGGAL_UPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UNIT_DITUJU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PENDAFTARAN");

                    b.HasIndex("PASIENID_PASIEN");

                    b.ToTable("TBL_PENDAFTARANs");
                });

            modelBuilder.Entity("Website_Klinik.Models.TBL_PASIEN", b =>
                {
                    b.HasOne("Website_Klinik.Models.TBL_ALAMAT", "ALAMAT")
                        .WithMany()
                        .HasForeignKey("ALAMATID_ALAMAT");

                    b.Navigation("ALAMAT");
                });

            modelBuilder.Entity("Website_Klinik.Models.TBL_PENDAFTARAN", b =>
                {
                    b.HasOne("Website_Klinik.Models.TBL_PASIEN", "PASIEN")
                        .WithMany()
                        .HasForeignKey("PASIENID_PASIEN");

                    b.Navigation("PASIEN");
                });
#pragma warning restore 612, 618
        }
    }
}
