USE KlinikDatabase
GO

DROP TABLE IF EXISTS Tbl_Alamat

CREATE TABLE Tbl_Alamat(
    ID_ALAMAT INTEGER IDENTITY(1,1) PRIMARY KEY,
    JALAN_PERUMAHAN VARCHAR(255),
    RT_RW VARCHAR(20),
    KECAMATAN VARCHAR(50),
    KABUPATEN VARCHAR(50),
    KOTA VARCHAR(50),
    PROVINSI VARCHAR(50)
)
GO

